import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css"
import React from "react";

const caculaValor = (valorConsumoAnterior: number, valorContaAnterior: number,
    ultimaLeituraDoPadrão: number, leituraAtualDoPadrão: number): string => {

    let valorUnitárioKWh = valorContaAnterior / valorConsumoAnterior;
    let consumoAtual = leituraAtualDoPadrão - ultimaLeituraDoPadrão;
    let valorAtualDaConta: number = consumoAtual * valorUnitárioKWh

    return `R$ ${valorAtualDaConta.toFixed(2)}`
}

const Teste: NextPage = () => {

    const [valorConsumoAnterior, setValorConsumoAnterior] = React.useState();
    const [valorContaAnterior, setValorContaAnterior] = React.useState();
    const [ultimaLeituraDoPadrão, setUltimaLeituraDoPadrão] = React.useState();
    const [leituraAtualDoPadrão, setLeituraAtualDoPadrão] = React.useState();
    const [valorAtualDaConta, setValorAtualDaConta] = React.useState("");

    const handleClick = (): void => {
        if (!valorConsumoAnterior || !valorContaAnterior || !ultimaLeituraDoPadrão
            || !leituraAtualDoPadrão) {
            alert("Por favor, preencha todos os campos antes de calcular o valor da conta!")
            return
        }

        setValorAtualDaConta(caculaValor(valorConsumoAnterior, valorContaAnterior,
            ultimaLeituraDoPadrão, leituraAtualDoPadrão))
        return
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Estimativa de valores</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Calcular o valor atual do consumo baseado na sua última
                    conta.</h1>
                <div className={valorAtualDaConta ? styles.resultado : ""} >
                    <h2 className={styles.textoResultado}>{valorAtualDaConta}</h2>
                </div>
                <div className={styles.form}>
                    <input
                        type="number"
                        value={valorConsumoAnterior ? valorConsumoAnterior : ""}
                        onChange={(event: any) => setValorConsumoAnterior(event.target.value)}
                        className={styles.input}
                        id="valorContaAnterior"
                        placeholder="Valor da conta anterior" />
                    <input
                        type="text"
                        value={valorContaAnterior ? valorContaAnterior : ""}
                        onChange={(event: any) => setValorContaAnterior(event.target.value)}
                        className={styles.input}
                        id="valorConsumoAnterior"
                        placeholder="kWh consumidos" />
                    <input
                        type="text"
                        value={ultimaLeituraDoPadrão ? ultimaLeituraDoPadrão : ""}
                        onChange={(event: any) => setUltimaLeituraDoPadrão(event.target.value)}
                        className={styles.input}
                        id="ultimaLeituraDoPadrão"
                        placeholder="Leitura no padrão" />
                    <input
                        type="text"
                        value={leituraAtualDoPadrão ? leituraAtualDoPadrão : ""}
                        onChange={(event: any) => setLeituraAtualDoPadrão(event.target.value)}
                        className={styles.input}
                        id="leituraAtualDoPadrão"
                        placeholder="Leitura no padrão hoje" />
                </div>

                <button type="submit" className={styles.button} onClick={() => handleClick()} >
                    <span>Calcular valor parcial</span>
                </button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://www.linkedin.com/in/adryellcabral/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Created by{'  Adryell Cabral'}
                    <span className={styles.logo}>
                        <Image src="/raiozinho.svg" alt="Raiozinho Icon" width={20} height={20} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Teste;