import { NextPage } from "next";
import styles from "../styles/Home.module.css"

const Teste: NextPage = () => {
    return (
        <div className={styles.container}>
            <head>
                <title>Página de teste</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </head>

            <main className={styles.main}>
                <h1 className={styles.title}>Página de teste</h1>
            </main>

            <footer>

            </footer>
        </div>
    )
}

export default Teste;